export const introduction = [
  'Welcome to the world.',
  'Here lies your self, a sleeping octopus.',
  'How peaceful.',
  "But now it's time to wake up.",
];

export const library = [
  'Oh.',
  'Oh dear.',
  'This is... hm.',
  'This is a library.',
  "Octopuses don't live in libraries.",
  'Octopodes?',
  'Octopi?',
  "In any case, you've gotta get out of here my friend.",
];

export const move = [
  '(psst)',
  '(hey human controlling the octopus)',
  '(you know video games right?)',
  '(ok well this is sort of like one of those)',
  '(use WASD to crawl around)',
  "(and when you're attached to a surface, use Space to jump off it)",
  '(you always jump in the direction of your cursor)',
  '(👍)',
];

export const book1: [string, string][] = [
  ['white', 'Sweet, you have control over all your limbs!'],
  ['red', 'Ahem.'],
  ['white', 'Oh shoot what was that?'],
  ['red', 'Hello Toothbrush.'],
  ['white', "Phew, it's talking to someone else."],
  ['red', 'I forget why I chose to name an octopus "Toothbrush", but whatevs.'],
  ['white', "nani"],
  ['red', 'Anyhow, I kidnapped you from your home'],
  ['red', 'and teleported you into this infinite library'],
  ['red', 'because I need an assistant.'],
  ['red', 'You see, I have so many books.'],
  ['red', "I don't have time to romp around in the library myself."],
  ['red', 'I need someone to find them for me.'],
  ['red', "That's where you come in."],
  ['red', "Actually, I happen to need a book from that room you're in."],
  ['red', 'That one over there, can you reach it for me?'],
];

export const book2: [string, string][] = [
  ['red', 'Impressive... you found it.'],
  ['red', "Hmm... I need another one in a bit, but it's further away..."],
  ['red', 'See if you can find your way over to it while I work on this.'],
];

export const book3: [string, string][] = [
  ['red', "Oh thanks! ... wait, this is Latin. I don't read Latin."],
  ['white', 'Who the heck is this disembodied voice being anyhow? ridiculous'],
  ['red', 'OK OK'],
  ['red', 'Ummmmmm'],
  ['red', 'Oh!'],
  ['red', 'Hahaha I was reading the bibliography upside down.'],
  ['red', 'The actual book I need is over yonder somewheres.'],
  ['red', 'Pretty please?'],
  ['white', "You'd better find a way out FAST or you'll, idk, suffocate or something."],
  ['white', "Y'know, like, with your gills? Do octofellows have those?"],
];

export const book4: [string, string][] = [
  ['white', '...'],
  ['red', 'Ha! Hilarious. Ah, what a life. Hum de do da dey...'],
  ['white', "Hey c'mon dude! Stop being such a jerk!"],
  ['red', 'Hrm? Who dat?'],
  ['white', "(wait, I'm the narrator, aren't I? I probably should be quiet)"],
  ['white', '(oh well)'],
  ['white', "Um... *deep voice* it's me, the octopod! I am... um... displeased"],
  ['red', "OK well lodge a complaint and I'll get back to you in 5-7 busi--"],
  ['white', 'NOT A COMPLAINT! um... a proposition'],
  ['red', "...?"],
  ['white', 'yes'],
  ['white', 'Elevator pitch:'],
  ['white', 'Do you like books?'],
  ['white', "Then you'll LOVE... um... A BOOK!"],
  ['white', 'I, the octopus, shall retrieve it for you!'],
  ['white', 'One of your choosing!'],
  ['white', 'For the low, low price of nothing, I just get it for you and go home.'],
  ['red', 'Oh cool, what a sweet deal!'],
  ['red', 'Um... yeah sure'],
  ['red', "You know, I've always wanted to read this one short story"],
  ['red', "It's a bit of a jog to reach, though. But since you asked..."],
];

export const close: [string, string][] = [
  ['red', '*sigh* It seems that you have brought me all the books I could ever want.'],
  ['white', 'Yussss'],
  ['red', "I have grown tired of books. They're just cephalopod juice on tree bread, after all."],
  ['red', 'This library should be destroyed. It can bring no more joy to anyone.'],
  ['red', 'Out of the great benevolence of my heart, I shall free you first.'],
  ['red', 'So long, and thanks for all the büx.'],
];

export const books = [
  [
    'Find enclosed a recipe for 3 (three) chocolate chip cookies. At *least*. Some people tell me this recipe yields two (2) or fewer cookies, but those people are absolute goobers if you ask me. These cookies should provide a nice ESCAPE (cough cough hint hint) from your otherwise boring existence.',
    'You will need: a) a a a a a a a sorry hold on one second',
    "My cat jumped on the keyboard and I can't find the backspace key. Anyway, you probably need some eggs and stuff, what, do I look like a chef to you? And some chocolate chips. Duh.",
    "Mix them together and you'll have a nice warm batch of chocolate chip cookie dough, except it's not warm yet because you probably forgot to bake it. Do I have to tell you everything? Honestly! It's like typing on a wall.",
    "Oh, and don't plagiarize my recipe. Lots of hours of R&D went into this. Lots.",
    "kthxbai",
  ],
  [
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam feugiat libero velit, eu aliquam diam maximus vel. Donec ac lorem quis sem pulvinar vulputate vel nec turpis. Proin ullamcorper turpis eu nisi malesuada, id egestas nulla interdum. Proin aliquam eleifend odio, ac consectetur metus placerat at. Etiam id vulputate justo. Maecenas bibendum metus ac arcu interdum condimentum. Sed a venenatis nisl. Praesent eu rutrum felis. Aenean porta ante volutpat ultricies auctor. Proin placerat gravida ex sit amet auctor. Nulla id pharetra sem, venenatis mattis ligula. Nulla quis velit non neque placerat imperdiet ac in odio.',
    'Nam dictum vel ipsum ut consequat. Maecenas in semper mauris. Cras scelerisque nisi bibendum neque placerat venenatis. Suspendisse bibendum quam nulla, ut pellentesque enim egestas id. Nullam iaculis metus vel nibh tempus, in eleifend massa pulvinar. Ut mollis risus enim, vel auctor ex fringilla sit amet. Donec congue enim mi, sed rhoncus massa aliquet sit amet. Donec non ante sed mauris pharetra hendrerit. In hac habitasse platea dictumst. Morbi dignissim odio eget velit ultricies posuere. Sed consequat viverra tincidunt. Praesent malesuada congue nisl nec elementum. Aenean sollicitudin leo quis hendrerit aliquam.',
    'Cras pulvinar felis in commodo aliquet. Aenean pulvinar ante lacus, in dapibus dolor faucibus sed. Etiam quis rhoncus dui. Nam quis dui dapibus, tempus eros at, faucibus sapien. Nulla congue, arcu vel faucibus ultrices, nunc enim blandit metus, eget elementum augue quam ac purus. Phasellus pulvinar facilisis ligula, vel ullamcorper velit ultricies at. Cras et est vestibulum, finibus justo quis, faucibus diam. Aenean vehicula nunc eget vestibulum convallis. Duis sollicitudin vel urna in rhoncus. Nunc non malesuada dui. Morbi congue augue orci, eu bibendum purus tempus at. Fusce ut nulla suscipit, mollis velit ut, eleifend nisl. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras ullamcorper pellentesque ligula in accumsan.',
    'Integer quis libero vel nunc gravida hendrerit quis congue mi. In mattis lectus et efficitur mattis. Cras ultrices congue tristique. Quisque urna magna, placerat egestas sem eget, finibus sollicitudin orci. Praesent eleifend facilisis augue sit amet gravida. Nulla in ante tortor. Nunc at semper orci, a iaculis dolor. Donec mollis ipsum sed vehicula volutpat.',
    'Praesent laoreet porttitor consequat. Nullam vel nunc vel orci dignissim tincidunt. Nulla egestas mauris quis est tempus, accumsan feugiat ex interdum. Duis eu purus nec magna eleifend malesuada. Nulla mollis lorem id imperdiet sagittis. Fusce venenatis cursus magna, vel consequat nisi blandit sit amet. In suscipit placerat quam id consequat. Mauris lacinia metus fermentum risus blandit, at pharetra quam tempus. Nulla sit amet ex malesuada, mattis mauris ut, pharetra massa. In congue nibh accumsan, hendrerit sem ac, convallis erat. Ut vulputate rutrum tempor.',
  ],
  [
    '... and then, Hardy Baker lifted up his cinnamon stick, crying "Avast ye the bad boy!" and spurted a scientifically propelled bolt of plasma-phase apple juice at his arch enemy, Wall-Wart.',
    '"(Oof!)"',
    "Thankfully, scientific propulsion is nonfatal. Wall-Wart fell back with a thuddish bellow and knocked over several boxes of cereal... including Hardy's platonic friend Flying Bee's favorite, Colonel Mustard. (It's mustard-colored.) She let out a terrific cry of grief and lunged toward the still-perfectly-fine box of cereal to coddle it.",
    '"Hardy, no!"',
    '"Hardy yes," Hardy uttered triumphantly. He strode toward Warty-boi. Drywall-Toad shrunk back and started quivering. Hardy pulled an arrow from his own quiver and loaded it into his sextuple-action compound bow.',
    '"Hardy, no." Weaker punctuation, but a stronger presence. Hardy spun around to see his estranged mentor Fumblyfoot striding toward him even more confidently than Hardy could himself manage. The teacher had once again become the teacher.',
    "Good ol' Fumfum started speaking in several tongues at once (you should have seen it, it was, like, so creepy). Three seconds later, poof! no more Wall-Wart.",
    '"He\'s in a better place now," Fumbly said with a grim on his face.',
    '"Ohohoho! What\'d I miss?"',
    'More spinning. Behold the wondrous Donald Bee. Unlike his sister Flying Bee, he has yet to master the art of flying. Hence the name.',
    '...',
    "It's a different universe, OK?! Their names aren't fixed at birth and such. All that jazz. It's very exciting!?",
    "Anywho, everyone was very annoyed at Don's late appearance to the party, so they proceeded to ...",
  ],
  [
    "\"Be careful what you wish for, you may receive it.\" --Anonymous",
    "Part I",
    "Without, the night was cold and wet, but in the small parlour of Laburnum villa the blinds were drawn and the fire burned brightly. Father and son were at chess; the former, who possessed ideas about the game involving radical chances, putting his king into such sharp and unnecessary perils that it even provoked comment from the white-haired old lady knitting placidly by the fire.",
    "\"Hark at the wind,\" said Mr. White, who, having seen a fatal mistake after it was too late, was amiably desirous of preventing his son from seeing it.",
    "\"I'm listening,\" said the latter grimly surveying the board as he stretched out his hand. \"Check.\"",
    "\"I should hardly think that he's come tonight, \" said his father, with his hand poised over the board.",
    "\"Mate,\" replied the son.",
    "\"That's the worst of living so far out,\" balled Mr. White with sudden and unlooked-for violence; \"Of all the beastly, slushy, out of the way places to live in, this is the worst. Path's a bog, and the road's a torrent. I don't know what people are thinking about. I suppose because only two houses in the road are let, they think it doesn't matter.\"",
    "\"Never mind, dear,\" said his wife soothingly; \"perhaps you'll win the next one.\"",
    "Mr. White looked up sharply, just in time to intercept a knowing glance between mother and son. the words died away on his lips, and he hid a guilty grin in his thin grey beard.",
    "\"There he is,\" said Herbert White as the gate banged to loudly and heavy footsteps came toward the door.",
    "The old man rose with hospitable haste and opening the door, was heard condoling with the new arrival. The new arrival also condoled with himself, so that Mrs. White said, \"Tut, tut!\" and coughed gently as her husband entered the room followed by a tall, burly man, beady of eye and rubicund of visage.",
    "\"Sergeant-Major Morris, \" he said, introducing him.",
    "The Sergeant-Major took hands and taking the proffered seat by the fire, watched contentedly as his host got out whiskey and tumblers and stood a small copper kettle on the fire.",
    "At the third glass his eyes got brighter, and he began to talk, the little family circle regarding with eager interest this visitor from distant parts, as he squared his broad shoulders in the chair and spoke of wild scenes and doughty deeds; of wars and plagues and strange peoples.",
    "\"Twenty-one years of it,\" said Mr. White, nodding at his wife and son. \"When he went away he was a slip of a youth in the warehouse. Now look at him.\"",
    "\"He don't look to have taken much harm.\" said Mrs. White politely.",
    "\"I'd like to go to India myself,\" said the old man, just to look around a bit, you know.\"",
    "\"Better where you are,\" said the Sergeant-Major, shaking his head. He put down the empty glass and sighning softly, shook it again.",
    "\"I should like to see those old temples and fakirs and jugglers,\" said the old man. \"what was that that you started telling me the other day about a monkey's paw or something, Morris?\"",
    "\"Nothing.\" said the soldier hastily. \"Leastways, nothing worth hearing.\"",
    "\"Monkey's paw?\" said Mrs. White curiously.",
    "\"Well, it's just a bit of what you might call magic, perhaps.\" said the Sergeant-Major off-handedly.",
    "His three listeners leaned forward eagerly. The visitor absent-mindedly put his empty glass to his lips and then set it down again. His host filled it for him again.",
    "\"To look at,\" said the Sergeant-Major, fumbling in his pocket, \"it's just an ordinary little paw, dried to a mummy.\"",
    "He took something out of his pocket and proffered it. Mrs. White drew back with a grimace, but her son, taking it, examined it curiously.",
    "\"And what is there special about it?\" inquired Mr. White as he took it from his son, and having examined it, placed it upon the table.",
    "\"It had a spell put on it by an old Fakir,\" said the Sergeant-Major, \"a very holy man. He wanted to show that fate ruled people's lives, and that those who interfered with it did so to their sorrow. He put a spell on it so that three separate men could each have three wishes from it.\"",
    "His manners were so impressive that his hearers were conscious that their light laughter had jarred somewhat.",
    "\"Well, why don't you have three, sir?\" said Herbert White cleverly.",
    "The soldier regarded him the way that middle age is wont to regard presumptuous youth.\"I have,\" he said quietly, and his blotchy face whitened.",
    "\"And did you really have the three wishes granted?\" asked Mrs. White.",
    "\"I did,\" said the sergeant-major, and his glass tapped against his strong teeth.",
    "\"And has anybody else wished?\" persisted the old lady.",
    "\"The first man had his three wishes. Yes,\" was the reply, \"I don't know what the first two were, but the third was for death. That's how I got the paw.\"",
    "His tones were so grave that a hush fell upon the group.",
    "\"If you've had your three wishes it's no good to you now then Morris,\" said the old man at last. \"What do you keep it for?\"",
    "The soldier shook his head. \"Fancy I suppose,\" he said slowly.\" I did have some idea of selling it, but I don't think I will. It has caused me enough mischief already. Besides, people won't buy. They think it's a fairy tale, some of them; and those who do think anything of it want to try it first and pay me afterward.\"",
    "\"If you could have another three wishes,\" said the old man, eyeing him keenly,\" would you have them?\"",
    "\"I don't know,\" said the other. \"I don't know.\"",
    "He took the paw, and dangling it between his forefinger and thumb, suddenly threw it upon the fire. White, with a slight cry, stooped down and snatched it off.",
    "\"Better let it burn,\" said the soldier solemnly.",
    "\"If you don't want it Morris,\" said the other, \"give it to me.\"",
    "\"I won't.\" said his friend doggedly. \"I threw it on the fire. If you keep it, don't blame me for what happens. Pitch it on the fire like a sensible man.\"",
    "The other shook his head and examined his possession closely. \"How do you do it?\" he inquired.",
    "\"Hold it up in your right hand, and wish aloud,\" said the Sergeant-Major, \"But I warn you of the consequences.\"",
    "\"Sounds like the 'Arabian Nights'\", said Mrs. White, as she rose and began to set the supper. \"Don't you think you might wish for four pairs of hands for me.\"",
    "Her husband drew the talisman from his pocket, and all three burst into laughter as the Seargent-Major, with a look of alarm on his face, caught him by the arm.",
    "\"If you must wish,\" he said gruffly, \"Wish for something sensible.\"",
    "Mr. White dropped it back in his pocket, and placing chairs, motioned his friend to the table. In the business of supper the talisman was partly forgotten, and afterward the three sat listening in an enthralled fashion to a second installment of the soldier's adventures in India.",
    "\"If the tale about the monkey's paw is not more truthful than those he has been telling us,\" said Herbert, as the door closed behind their guest, just in time to catch the last train, \"we shan't make much out of it.\"",
    "\"Did you give anything for it, father?\" inquired Mrs. White, regarding her husband closely.",
    "\"A trifle,\" said he, colouring slightly, \"He didn't want it, but I made him take it. And he pressed me again to throw it away.\"",
    "\"Likely,\" said Herbert, with pretended horror. \"Why, we're going to be rich, and famous, and happy. Wish to be an emperor, father, to begin with; then you can't be henpecked.\"",
    "He darted around the table, pursued by the maligned Mrs White armed with an antimacassar.",
    "Mr. White took the paw from his pocket and eyed it dubiously. \"I don't know what to wish for, and that's a fact,\" he said slowly. It seems to me I've got all I want.\"",
    "\"If you only cleared the house, you'd be quite happy, wouldn't you!\" said Herbert, with his hand on his shoulder. \"Well, wish for two hundred pounds, then; that'll just do it.\"",
    "His father, smiling shamefacedly at his own credulity, held up the talisman, as his son, with a solemn face, somewhat marred by a wink at his mother, sat down and struck a few impressive chords.",
    "\"I wish for two hundred pounds,\" said the old man distinctly.",
    "A fine crash from the piano greeted his words, interrupted by a shuddering cry from the old man. His wife and son ran toward him.",
    "\"It moved,\" he cried, with a glance of disgust at the object as it lay on the floor. \"As I wished, it twisted in my hand like a snake.\"",
    "\"Well, I don't see the money,\" said his son, as he picked it up and placed it on the table, \"and I bet I never shall.\"",
    "\"It must have been your fancy, father,\" said his wife, regarding him anxiously.",
    "He shook his head. \"Never mind, though; there's no harm done, but it gave me a shock all the same.\"",
    "They sat down by the fire again while the two men finished their pipes. Outside, the wind was higher than ever, an the old man started nervously at the sound of a door banging upstairs. A silence unusual and depressing settled on all three, which lasted until the old couple rose to retire for the rest of the night.",
    "\"I expect you'll find the cash tied up in a big bag in the middle of your bed,\" said Herbert, as he bade them good night, \" and something horrible squatting on top of your wardrobe watching you as you pocket your ill-gotten gains.\"",
    "He sat alone in the darkness, gazing at the dying fire, and seeing faces in it. The last was so horrible and so simian that he gazed at it in amazement. It got so vivid that, with a little uneasy laugh, he felt on the table for a glass containing a little water to throw over it. His hand grasped the monkey's paw, and with a little shiver he wiped his hand on his coat and went up to bed.",
    "Part II",
    "In the brightness of the wintry sun next morning as it streamed over the breakfast table he laughed at his fears. There was an air of prosaic wholesomeness about the room which it had lacked on the previous night, and the dirty, shriveled little paw was pitched on the side-board with a carelessness which betokened no great belief in its virtues.",
    "\"I suppose all old soldiers are the same,\" said Mrs White. \"The idea of our listening to such nonsense! How could wishes be granted in these days? And if they could, how could two hundred pounds hurt you, father?\"",
    "\"Might drop on his head from the sky,\" said the frivolous Herbert.",
    "\"Morris said the things happened so naturally,\" said his father, \"that you might if you so wished attribute it to coincidence.\"",
    "\"Well don't break into the money before I come back,\" said Herbert as he rose from the table. \"I'm afraid it'll turn you into a mean, avaricious man, and we shall have to disown you.\"",
    "His mother laughed, and following him to the door, watched him down the road; and returning to the breakfast table, was very happy at the expense of her husband's credulity. All of which did not prevent her from scurrying to the door at the postman's knock, nor prevent her from referring somewhat shortly to retired Sergeant-Majors of bibulous habits when she found that the post brought a tailor's bill.",
    "\"Herbert will have some more of his funny remarks, I expect, when he comes home,\" she said as they sat at dinner.",
    "\"I dare say,\" said Mr. White, pouring himself out some beer; \"but for all that, the thing moved in my hand; that I'll swear to.\"",
    "\"You thought it did,\" said the old lady soothingly.",
    "\"I say it did,\" replied the other. \"There was no thought about it; I had just - What's the matter?\"",
    "His wife made no reply. She was watching the mysterious movements of a man outside, who, peering in an undecided fashion at the house, appeared to be trying to make up his mind to enter. In mental connexion with the two hundred pounds, she noticed that the stranger was well dressed, and wore a silk hat of glossy newness. Three times he paused at the gate, and then walked on again. The fourth time he stood with his hand upon it, and then with sudden resolution flung it open and walked up the path. Mrs White at the same moment placed her hands behind her, and hurriedly unfastening the strings of her apron, put that useful article of apparel beneath the cushion of her chair.",
    "She brought the stranger, who seemed ill at ease, into the room. He gazed at her furtively, and listened in a preoccupied fashion as the old lady apologized for the appearance of the room, and her husband's coat, a garment which he usually reserved for the garden. She then waited as patiently as her sex would permit for him to broach his business, but he was at first strangely silent.",
    "\"I - was asked to call,\" he said at last, and stooped and picked a piece of cotton from his trousers. \"I come from 'Maw and Meggins.' \"",
    "The old lady started. \"Is anything the matter?\" she asked breathlessly. \"Has anything happened to Herbert? What is it? What is it?",
    "Her husband interposed. \"There there mother,\" he said hastily. \"Sit down, and don't jump to conclusions. You've not brought bad news, I'm sure sir,\" and eyed the other wistfully.",
    "\"I'm sorry - \" began the visitor.",
    "\"Is he hurt?\" demanded the mother wildly.",
    "The visitor bowed in assent.\"Badly hurt,\" he said quietly, \"but he is not in any pain.\"",
    "\"Oh thank God!\" said the old woman, clasping her hands. \"Thank God for that! Thank - \"",
    "She broke off as the sinister meaning of the assurance dawned on her and she saw the awful confirmation of her fears in the others averted face. She caught her breath, and turning to her slower-witted husband, laid her trembling hand on his. There was a long silence.",
    "\"He was caught in the machinery,\" said the visitor at length in a low voice.",
    "\"Caught in the machinery,\" repeated Mr. White, in a dazed fashion,\"yes.\"",
    "He sat staring out the window, and taking his wife's hand between his own, pressed it as he had been wont to do in their old courting days nearly forty years before.",
    "\"He was the only one left to us,\" he said, turning gently to the visitor. \"It is hard.\"",
    "The other coughed, and rising, walked slowly to the window. \" The firm wishes me to convey their sincere sympathy with you in your great loss,\" he said, without looking round. \"I beg that you will understand I am only their servant and merely obeying orders.\"",
    "There was no reply; the old woman’s face was white, her eyes staring, and her breath inaudible; on the husband's face was a look such as his friend the sergeant might have carried into his first action.",
    "\"I was to say that Maw and Meggins disclaim all responsibility,\" continued the other. \"They admit no liability at all, but in consideration of your son's services, they wish to present you with a certain sum as compensation.\"",
    "Mr. White dropped his wife's hand, and rising to his feet, gazed with a look of horror at his visitor. His dry lips shaped the words, \"How much?\"",
    "\"Two hundred pounds,\" was the answer.",
    "Unconscious of his wife's shriek, the old man smiled faintly, put out his hands like a sightless man, and dropped, a senseless heap, to the floor.",
    "Part III",
    "In the huge new cemetery, some two miles distant, the old people buried their dead, and came back to the house steeped in shadows and silence. It was all over so quickly that at first they could hardly realize it, and remained in a state of expectation as though of something else to happen - something else which was to lighten this load, too heavy for old hearts to bear.",
    "But the days passed, and expectations gave way to resignation - the hopeless resignation of the old, sometimes mis-called apathy. Sometimes they hardly exchanged a word, for now they had nothing to talk about, and their days were long to weariness.",
    "It was about a week after that the old man, waking suddenly in the night, stretched out his hand and found himself alone. The room was in darkness, and the sound of subdued weeping came from the window. He raised himself in bed and listened.",
    "\"Come back,\" he said tenderly. \"You will be cold.\"",
    "\"It is colder for my son,\" said the old woman, and wept afresh.",
    "The sounds of her sobs died away on his ears. The bed was warm, and his eyes heavy with sleep. He dozed fitfully, and then slept until a sudden wild cry from his wife awoke him with a start.",
    "\"THE PAW!\" she cried wildly. \"THE MONKEY'S PAW!\"",
    "He started up in alarm. \"Where? Where is it? What’s the matter?\"",
    "She came stumbling across the room toward him. \"I want it,\" she said quietly. \"You've not destroyed it?\"",
    "\"It's in the parlour, on the bracket,\" he replied, marveling. \"Why?\"",
    "She cried and laughed together, and bending over, kissed his cheek.",
    "\"I only just thought of it,\" she said hysterically. \"Why didn't I think of it before? Why didn't you think of it?\"",
    "\"Think of what?\" he questioned.",
    "\"The other two wishes,\" she replied rapidly. \"We've only had one.\"",
    "\"Was not that enough?\" he demanded fiercely.",
    "\"No,\" she cried triumphantly; \"We'll have one more. Go down and get it quickly, and wish our boy alive again.\"",
    "The man sat in bed and flung the bedclothes from his quaking limbs.\"Good God, you are mad!\" he cried aghast. \"Get it,\" she panted; \"get it quickly, and wish - Oh my boy, my boy!\"",
    "Her husband struck a match and lit the candle. \"Get back to bed he said unsteadily. \"You don't know what you are saying.\"",
    "\"We had the first wish granted,\" said the old woman, feverishly; \"why not the second?\"",
    "\"A coincidence,\" stammered the old man.",
    "\"Go get it and wish,\" cried his wife, quivering with excitement.",
    "The old man turned and regarded her, and his voice shook. \"He has been dead ten days, and besides he - I would not tell you else, but - I could only recognize him by his clothing. If he was too terrible for you to see then, how now?\"",
    "\"Bring him back,\" cried the old woman, and dragged him towards the door. \"Do you think I fear the child I have nursed?\"",
    "He went down in the darkness, and felt his way to the parlour, and then to the mantlepiece. The talisman was in its place, and a horrible fear that the unspoken wish might bring his mutilated son before him ere he could escape from the room seized up on him, and he caught his breath as he found that he had lost the direction of the door. His brow cold with sweat, he felt his way round the table, and groped along the wall until he found himself in the small passage with the unwholesome thing in his hand.",
    "Even his wife's face seemed changed as he entered the room. It was white and expectant, and to his fears seemed to have an unnatural look upon it. He was afraid of her.",
    "\"WISH!\" she cried in a strong voice.",
    "\"It is foolish and wicked,\" he faltered.",
    "\"WISH!\" repeated his wife.",
    "He raised his hand. \"I wish my son alive again.\"",
    "The talisman fell to the floor, and he regarded it fearfully. Then he sank trembling into a chair as the old woman, with burning eyes, walked to the window and raised the blind.",
    "He sat until he was chilled with the cold, glancing occasionally at the figure of the old woman peering through the window. The candle-end, which had burned below the rim of the china candlestick, was throwing pulsating shadows on the ceiling and walls, until with a flicker larger than the rest, it expired. The old man, with an unspeakable sense of relief at the failure of the talisman, crept back back to his bed, and a minute afterward the old woman came silently and apathetically beside him.",
    "Neither spoke, but sat silently listening to the ticking of the clock. A stair creaked, and a squeaky mouse scurried noisily through the wall. The darkness was oppressive, and after lying for some time screwing up his courage, he took the box of matches, and striking one, went downstairs for a candle.",
    "At the foot of the stairs the match went out, and he paused to strike another; and at the same moment a knock came so quiet and stealthy as to be scarcely audible, sounded on the front door.",
    "The matches fell from his hand and spilled in the passage. He stood motionless, his breath suspended until the knock was repeated. Then he turned and fled swiftly back to his room, and closed the door behind him. A third knock sounded through the house.",
    "\"WHAT’S THAT?\" cried the old woman, starting up.",
    "\"A rat,\" said the old man in shaking tones - \"a rat. It passed me on the stairs.\"",
    "His wife sat up in bed listening. A loud knock resounded through the house.",
    "\"It's Herbert!\"",
    "She ran to the door, but her husband was before her, and catching her by the arm, held her tightly.",
    "\"What are you going to do?\" he whispered hoarsely.",
    "\"It's my boy; it's Herbert!\" she cried, struggling mechanically. \"I forgot it was two miles away. What are you holding me for? Let go. I must open the door.\"",
    "\"For God's sake don't let it in,\" cried the old man, trembling.",
    "\"You're afraid of your own son,\" she cried struggling. \"Let me go. I'm coming, Herbert; I'm coming.\"",
    "There was another knock, and another. The old woman with a sudden wrench broke free and ran from the room. Her husband followed to the landing, and called after her appealingly as she hurried downstairs. He heard the chain rattle back and the bolt drawn slowly and stiffly from the socket. Then the old woman’s voice, strained and panting.",
    "\"The bolt,\" she cried loudly. \"Come down. I can't reach it.\"",
    "But her husband was on his hands and knees groping wildly on the floor in search of the paw. If only he could find it before the thing outside got in. A perfect fusillade of knocks reverberated through the house, and he heard the scraping of a chair as his wife put it down in the passage against the door. He heard the creaking of the bolt as it came slowly back, and at the same moment he found the monkey's paw, and frantically breathed his third and last wish.",
    "The knocking ceased suddenly, although the echoes of it were still in the house. He heard the chair drawn back, and the door opened. A cold wind rushed up the staircase, and a long loud wail of disappointment and misery from his wife gave him the courage to run down to her side, and then to the gate beyond. The street lamp flickering opposite shone on a quiet and deserted road.\n"
  ],
];

export const credits = [
  'Thanks for playing!',
  '',
  'books 2 and 4:',
  'Lorem Ipsum - Cicero',
  "The Monkey's Paw - W. W. Jacobs",
  '',
  'this game:',
  'design - Sam Estep',
  'code - Sam Estep',
  'art - Sam Estep',
  'story - Sam Estep',
  'music - Sam Estep',
  '',
  'special thanks:',
  'ESLint, GitHub, Phaser,',
  'Travis CI, TypeScript, Yarn',
];
